plugins {
id 'com.android.application'
}

android {
namespace "simple.shell.runner"
compileSdk 34

lint {
checkReleaseBuilds false
}

defaultConfig {  
    applicationId "simple.shell.runner"  
    minSdk 29
    targetSdk 37
    versionCode 1
    versionName "1.0"  
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
    }  
}

}

dependencies {
}
